# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-08 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='client_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('membership_level', models.CharField(default='Regular', max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('client_description', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(default='Skeleton', max_length=20)),
                ('product_type', models.CharField(default='Watch', max_length=20)),
                ('product_origin', models.CharField(default='Casio', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.AddField(
            model_name='client_profile',
            name='preffered_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Client.products'),
        ),
    ]
